config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :incomes
  resources :categories

  get '/dashboard' => 'dashboard#index', as: :dashboard
  post '/generate_monthly_balance' => 'dashboard#generate_monthly_balance', as: :generate_monthly_balance
  get '/configurations' => 'configurations#index', as: :configurations
  patch '/configurations/change_theme' => 'configurations#change_theme', as: :change_theme
  patch '/configurations/change_email_notifications' => 'configurations#change_email_notifications',
        as: :change_email_notifications
  patch '/configurations/change_push_notifications' => 'configurations#change_push_notifications',
        as: :change_push_notifications

  get '/auth/google_oauth2/callback', to: 'providers#start_google_session'

  get 'service-worker' => 'pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'pwa#manifest', as: :pwa_manifest
  post 'push_subscriptions' => 'push_subscriptions#create', as: :push_subscriptions
  delete 'push_subscriptions' => 'push_subscriptions#destroy', as: :destroy_push_subscription

  revise_auth

  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_search

  include BalanceHelper

  def index
    @result = @q.result.includes(expenses: :category, incomes: :category).order(created_at: :desc).first

    if @result
      @all_incomes_and_expenses = @result.all_incomes_and_expenses if @result
      @total_incomes = total_incomes
      @total_expenses = total_expenses
      @total_balance = total_balance
      @total_fixed_expenses = total_fixed_expenses
      @total_fixed_incomes = total_fixed_incomes
    end

    @month = @q.month_eq
    @year = @q.year_eq
  end

  def generate_monthly_balance
    month = params[:month].to_i
    year = params[:year].to_i
    MonthlyBalanceService.new(current_user, month, year).generate_monthly_balance

    if current_user.balances.where(month:, year:).empty?
      redirect_to root_path(q: {
                              month_eq: month,
                              year_eq: year
                            }), flash: { notice: 'Não foi possível gerar o balanço!', style: 'error' }
      return
    end

    redirect_to root_path(q: {
                            month_eq: month,
                            year_eq: year
                          }), flash: { notice: 'Balanço gerado com sucess!', style: 'success' }
  end

  private

  def set_search
    if params[:q].blank?
      params[:q] = {
        month_eq: Time.now.mon,
        year_eq: Time.now.year
      }
    end
    @q = current_user.balances.ransack(params[:q])
  end

  def total_incomes
    @total_incomes ||= @result.try(:incomes)&.sum(:value)
  end

  def total_expenses
    @total_expenses ||= @result.try(:expenses)&.sum(:value)
  end

  def total_fixed_expenses
    @total_fixed_expenses ||= @result.try(:expenses).where(fixed: true)&.sum(:value)
  end

  def total_fixed_incomes
    @total_fixed_incomes ||= @result.try(:incomes).where(fixed: true)&.sum(:value)
  end

  def total_balance
    @total_balance ||= @result.try(:balance)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def positive_check(number)
    number.positive? ? 'bg-success' : 'bg-error'
  end

  def positive_bool(number)
    number.positive? ? true : false
  end
end

app/views/dashboard/index.html.erb
<div class="grid gap-8">
  <div class="grid gap-2">
    <div class="flex items-center justify-between">
      <%= search_form_for @q, url: dashboard_path do |f| %>
        <%= f.search_field :month_eq, value: @month == 1 ? 12 : @month - 1 , hidden: true %>
        <%= f.search_field :year_eq, value: @month == 1 ? @year - 1 : @year, hidden: true %>
        <button type="submit" class="btn btn-sm btn-primary">
          <i class="fa-solid fa fa-arrow-left" aria-hidden="true"></i></i>
        <p class="hidden md:block">Mês anterior</p>
      </button>
    <% end %>
    <h1 class="md:text-xl font-semibold">Balanço de <%= get_month_text(@month) %>/<%= @year %></h1>
    <%= search_form_for @q, url: dashboard_path do |f| %>
      <%= f.search_field :month_eq, value: @month == 12 ? 1 : @month + 1, hidden: true %>
      <%= f.search_field :year_eq, value: @month == 12 ? @year + 1 : @year, hidden: true %>
      <button type="submit" class="btn btn-sm btn-primary">
        <p class="hidden md:block">Mês seguinte</p>
        <i class="fa fa-arrow-right" aria-hidden="true"></i>
      </button>
    <% end %>
  </div>
</div>
<% if @all_incomes_and_expenses.nil? %>
  <div class="grid place-content-center gap-2">
    <h1 class="text-center text-2xl font-bold h-full mt-32">Nenhum balanço encontrado...</h1>
    <%= form_with url: generate_monthly_balance_path, method: :post do %>
      <%= hidden_field_tag :month, @month %>
      <%= hidden_field_tag :year, @year %>
      <%= submit_tag "Gerar o balanço do mês #{get_month_text(@month)}", class: "btn btn-primary mx-auto w-full" %>
    <% end %>
    <small>Todos as receitas e despesas fixa serão importadas*</small>
  </div>
<% else %>
  <% if @total_balance != 0 %>
    <h2 class="text-center text-white text-xl font-semibold p-3 rounded-md <%= positive_bool(@total_balance) ? 'bg-success animate-pulse' : 'bg-error animate-pulse' %> w-fit">Seu balanço está <%= positive_bool(@total_balance) ? "positivo, Parabéns!!! 🤑🎉": "negativo, tente se organizar melhor! 😰💸" %></h2>
  <% end %>
  <section class="grid gap-6">
    <h1 class="text-3xl font-bold">Balanço</h1>
    <div class="relative p-5 rounded-md overflow-hidden h-32 md:w-1/2 <%= positive_check(@total_balance) %>">
      <div class="relative z-10 mb-4 text-white text-5xl leading-none font-semibold"><%= format_brl_currency(@total_balance) %></div>
      <div class="relative z-10 text-gray-200 leading-none font-semibold text-xl">Balanço Atual</div>
      <i class="fa-solid fa-scale-balanced absolute right-4 bottom-2 h-40 w-40 -mr-8 -mb-8 opacity-40 <%= positive_bool(@total_balance) ? 'text-green-700' : 'text-red-700' %>"></i>
    </div>
  </section>
  <section class="grid lg:grid-cols-3 gap-2">
    <h2 class="font-semibold text-2xl md:col-span-3">Resumo</h2>
    <div class="relative p-5 bg-info rounded-md overflow-hidden">
      <div class="relative z-10 mb-4 text-white text-4xl leading-none font-semibold"><%= format_brl_currency(@total_incomes) %></div>
      <div class="relative z-10 text-sky-200 leading-none font-semibold">Receitas Totais</div>
      <i class="fa-solid fa-hand-holding-dollar absolute right-6 bottom-6 h-32 w-32 -mr-8 -mb-8 text-sky-700 opacity-40"></i>
    </div>
    <div class="relative p-5 bg-error rounded-md overflow-hidden">
      <div class="relative z-10 mb-4 text-white text-4xl leading-none font-semibold"><%= format_brl_currency(@total_expenses) %></div>
      <div class="relative z-10 text-red-200 leading-none font-semibold">Despesas Totais</div>
      <i class="fa-solid fa-arrow-down-wide-short absolute right-2 bottom-4 h-32 w-32 -mr-8 -mb-8 text-red-700 opacity-40"></i>
    </div>
    <h2 class="font-semibold text-2xl md:col-span-3 md:hidden mt-8">Movimentações Fixas</h2>
    <div class="grid grid-cols-2 gap-2">
      <div class="relative p-5 bg-info rounded-md overflow-hidden">
        <div class="relative z-10 mb-4 text-white text-2xl md:text-4xl leading-none font-semibold"><%= format_brl_currency(@total_fixed_incomes) %></div>
        <div class="relative z-10 text-sky-200 leading-none font-semibold">Receitas Fixas</div>
        <i class="fa-solid fa-money-bill-trend-up absolute right-2 bottom-4 h-24 w-24 -mr-4 -mb-6 text-sky-700 opacity-40 md:opacity-40"></i>
      </div>
      <div class="relative p-5 bg-gradient-to-r bg-error rounded-md overflow-hidden">
        <div class="relative z-10 mb-4 text-white text-2xl md:text-4xl leading-none font-semibold"><%= format_brl_currency(@total_fixed_expenses) %></div>
        <div class="relative z-10 text-red-200 leading-none font-semibold">Despesas Fixas</div>
        <i class="fa-solid fa-arrow-trend-down absolute right-2 bottom-4 h-24 w-24 -mr-1 -mb-8 text-red-700 opacity-40 md:opacity-40"></i>
      </div>
    </div>
  </section>
  <section class="grid gap-2">
    <h2 class="text-xl font-semibold">Links Rápidos</h2>
    <div class="flex flex-wrap items-center gap-2">
      <%= link_to new_income_path, class: "btn btn-primary" do %>
        <i class="fa-solid fa-arrow-up-wide-short"></i>
        Nova Receita
      <% end %>
      <%= link_to new_expense_path, class: "btn btn-primary" do %>
        <i class="fa-solid fa-arrow-down-wide-short"></i>
        Nova Despesa
      <% end %>
      <%= link_to profile_path, class: "btn btn-primary" do %>
        <i class="fa-solid fa-user"></i>
        Perfil
      <% end %>
      <%= link_to configurations_path, class: "btn btn-primary" do %>
        <i class="fa-solid fa-cog"></i>
        Configurações
      <% end %>
    </section>
    <section>
      <h3 class="text-xl font-semibold mt-3">Resumo do Mês Atual:</h3>
      <div id="expenses" class="overflow-x-auto my-6">
        <% if @all_incomes_and_expenses %>
          <%= render 'shared/desktop_table', values: @all_incomes_and_expenses %>
          <%= render 'shared/mobile_table', values: @all_incomes_and_expenses %>
        <% else %>
          <p class="text-center">Nenhum registro encontrado.</p>
        <% end %>
      </div>
    </section>
  <% end %>
</div>