config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :incomes
  resources :categories

  get '/dashboard' => 'dashboard#index', as: :dashboard
  post '/generate_monthly_balance' => 'dashboard#generate_monthly_balance', as: :generate_monthly_balance
  get '/configurations' => 'configurations#index', as: :configurations
  patch '/configurations/change_theme' => 'configurations#change_theme', as: :change_theme
  patch '/configurations/change_email_notifications' => 'configurations#change_email_notifications',
        as: :change_email_notifications
  patch '/configurations/change_push_notifications' => 'configurations#change_push_notifications',
        as: :change_push_notifications

  get '/auth/google_oauth2/callback', to: 'providers#start_google_session'

  get 'service-worker' => 'pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'pwa#manifest', as: :pwa_manifest
  post 'push_subscriptions' => 'push_subscriptions#create', as: :push_subscriptions
  delete 'push_subscriptions' => 'push_subscriptions#destroy', as: :destroy_push_subscription

  revise_auth

  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  belongs_to :balance
  belongs_to :category

  before_validation :set_balance

  validates :value, presence: true
  # validates :day, presence: true, if: :fixed?
  validates :date, presence: true
  
  after_save :update_balance_value

  include UpdateBalanceValue
  include SetBalance

  def self.ransackable_attributes(_auth_object = nil)
    %w[balance_id category_id created_at day description fixed id updated_at
       user_id value date]
  end

  def income_month_year
    created_at.strftime('%B/%Y')
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_income, only: %i[show edit update destroy]
  before_action :format_comma_to_dot, only: %i[create update]
  before_action :load_income_categories, only: %i[new edit create update]
  include BalanceHelper

  def index
    @q = current_user.incomes.includes(:category).order(date: :desc).ransack(params[:q])
    @pagy, @incomes = pagy_countless(@q.result.includes(:category), limit: 15)
  end

  def show; end

  def new
    @income = current_user.incomes.build
  end

  def edit; end

  def create
    @income = current_user.incomes.build(income_params)
    @income.balance_id = @user_actual_month_yeah_balance.id

    respond_to do |format|
      if @income.save
        format.html do
          redirect_to root_path(q: {
                                  month_eq: @income.date.month,
                                  year_eq: @income.date.year
                                }), flash: { notice: 'Receita adicionada com sucesso', style: 'success' }
        end
        format.json { render :show, status: :created, location: @income }
      else
        format.html do
          render :new, status: :unprocessable_entity, flash: { notice: 'Erro ao adicionar a receita', style: 'error' }
        end
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if params[:fixed] == false
      @income.day = nil
      @income.save
    end

    respond_to do |format|
      if @income.update(income_params)
        format.html do
          redirect_to root_path(q: {
                                  month_eq: @income.date.month,
                                  year_eq: @income.date.year
                                }), flash: { notice: 'Receita atualizada com sucesso', style: 'success' }
        end
        format.json { render :show, status: :ok, location: @income }
      else
        format.html do
          render :edit, status: :unprocessable_entity, flash: { notice: 'Erro ao atualizar a receita', style: 'error' }
        end
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @income.destroy!

    respond_to do |format|
      format.html do
        redirect_to root_path(q: {
                                month_eq: @income.date.month,
                                year_eq: @income.date.year
                              }), flash: { notice: 'Receita removida com sucesso', style: 'success' }
      end
      format.json { head :no_content }
    end
  end

  private

  def set_income
    @income = Income.find(params[:id])
  end

  def income_params
    params.require(:income).permit(:value, :description, :fixed, :user_id, :balance_id, :category_id, :day, :date)
  end

  def format_comma_to_dot
    params[:income][:value] = params[:income][:value].to_s.gsub('R$', '').gsub(',', '.')
  end

  def load_income_categories
    @incomes_categories = Category.user_global(current_user).incomes
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper

  def submit_income_button_text
    @income.new_record? ? "Gerar nova receita" : "Atualizar receita"
  end
end

app/views/incomes/_form.html.erb
<%= form_with(model: income, class: "contents", data: { controller: 'masks income-form' }) do |form| %>
  <% if income.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2>Atenção:</h2>
      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :value, "Valor", class: "font-semibold text-lg" %>
    <%= form.text_field :value, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full", data: { masks_target: 'brl' }, placeholder: "R$" %>
  </div>
  <div class="my-5">
    <%= form.label :description, "Descrição", class: "font-semibold text-lg" %>
    <%= form.text_field :description, placeholder: "Ex: Compras do mês", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="flex flex-col md:flex-row md:items-center gap-4 md:gap-6">
    <div class="grid">
      <div class="flex items-center gap-4">
        <%= form.label :fixed, "Marcar como receita fixa?", class: "font-semibold text-lg" %>
        <%= form.check_box :fixed, class: "checkbox"%>
      </div>
      <small>Receitas fixas são automaticamente geradas todo mês.</small>
    </div>
    <!--<div class="hidden items-center gap-4" data-income-form-target="day">
      <%= form.label :day, "Dia:", class: "font-semibold text-lg" %>
      <%= form.text_field :day, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-28", placeholder: "Ex: 10", data: { income_form_target: 'dayInput' } %>
    </div>-->
  </div>
  <div class="my-5">
    <%= form.label :date, "Data", class: "font-semibold text-lg" %>
    <%= form.date_field :date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :category_id, "Categoria", class: "font-semibold text-lg" %>
    <%= form.collection_select :category_id, @incomes_categories, :id, :name, { prompt: "Selecione a categoria" }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="flex justify-between items-center">
    <%= link_to @income, class: "btn btn-secondary" do %>
      <i class="fa fa-arrow-left" aria-hidden="true"></i>
      Voltar
    <% end %>
    <%= form.submit submit_income_button_text, class: "btn btn-primary rounded-lg py-3 px-5 text-white font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<div id="<%= dom_id income %>" class="grid gap-3">
  <p class="grid md:flex gap-2">
    <strong class="block font-medium">
      <i class="fas fa-money-bill"></i>
      Valor:
    </strong>
    <span>
      <%= format_brl_currency(income.value) %>
    </span>
  </p>
  <p class="grid md:flex md:flex-wrap gap-2">
    <strong class="block font-medium">
      <i class="fas fa-align-left"></i>
      Descrição:
    </strong>
    <span class="break-all md:break-normal">
      <%= income.description %>
    </span>
  </p>
  <% if income.fixed %>
    <div class="flex items-center gap-2">
      <strong class="block font-medium">
        <i class="fas fa-check"></i>
        Todo dia:
      </strong>
      <%= income.day %>
    </div>
  <% end %>
  <p class="grid md:flex gap-2">
    <strong class="block font-medium mb-1">
      <i class="fas fa-calendar-day"></i>
      Balanço do Mês:
    </strong>
    <%= income.balance.month %>
  </p>
  <p class="grid md:flex gap-2">
    <strong class="block font-medium mb-1">
      <i class="fas fa-tags"></i>
      Categoria:
    </strong>
    <%= income.category.name %>
  </p>
</div>

app/views/incomes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex items-center justify-between">
    <h1 class="font-bold text-4xl">Editar Receita</h1>
    <%= link_to incomes_path, class: "btn btn-info flex" do %>
      <i class="fa fa-list mb-1" aria-hidden="true"></i>
      Listar Receitas
    <% end %>
  </div>
  <%= render "form", income: @income %>
</div>

app/views/incomes/index.html.erb
<div class="w-full">
  <% content_for :title, "Incomes" %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl md:text-4xl">Receitas</h1>
    <%= link_to new_income_path, class: "btn btn-primary btn-sm md:btn-md" do %>
      <i class="fa-solid fa-plus  text-xl"></i>
      <span class="text-lg">Nova receita</span>
    <% end %>
  </div>
  <div class="grid gap-4" data-controller="search">
    <div class="mt-4 grid gap-2">
      <h2 class="font-bold text-lg md:text-xl">Buscas Rápidas:</h2>
      <div class="flex md:flex-row gap-2 overflow-x-auto">
        <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
          <%= f.search_field :date_gteq, value: Time.now.beginning_of_month, hidden: true %>
          <%= f.search_field :date_lteq, value: Time.now.end_of_month, hidden: true %>
          <%= f.submit "Mês Atual", class: "btn btn-primary btn-sm", data: { action: 'click->search#showClearButton'} %>
        <% end %>
        <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
          <%= f.search_field :date_gteq, value: Time.now.beginning_of_month.last_month, hidden: true ,data: { action: 'click->search#search'}%>
          <%= f.search_field :date_lteq, value: Time.now.end_of_month.last_month, hidden: true %>
          <%= f.submit "Mês Passado", class: "btn btn-primary btn-sm", data: { action: 'click->search#showClearButton'} %>
        <% end %>
        <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
          <%= f.check_box :fixed_eq, checked: true, hidden: true %>
          <%= f.submit "Receitas Fixas", class: "btn btn-primary btn-sm", data: { action: 'click->search#showClearButton'} %>
        <% end %>
        <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
          <%= f.check_box :fixed_eq, checked: false, hidden: true %>
          <%= f.submit "Receitas Avulsas", class: "btn btn-primary btn-sm", data: { action: 'click->search#showClearButton'} %>
        <% end %>
      </div>
    </div>
    <div class="grid gap-4">
      <div class="flex items-center gap-2 overflow-x-auto">
        <button data-action="search#toggleText" class="btn btn-primary rounded-sm btn-sm">
          <i class="fa fa-search h-4 w-4" aria-hidden="true"></i>
        </button>
        <button class="btn btn-primary rounded-sm btn-sm" onclick="data.showModal()">
          Datas
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </button>
        <button class="btn btn-primary rounded-sm btn-sm" onclick="categories.showModal()">
          Categorias
          <i class="fa fa-list" aria-hidden="true"></i>
        </button>
      </div>
      <%= search_form_for @q, class: "grid gap-2", data: { turbo_frame: :results, turbo_action: :advance, search_target: 'form' } do |f| %>
        <div class="flex md:items-center flex-col md:flex-row gap-4">
          <div class="flex-col md:flex-row md:items-center gap-1 md:gap-4 w-full hidden" data-search-target="description">
            <%= f.label :description, "Busca", class: "font-semibold" %>
            <%= f.search_field :description_cont, class: "input input-sm input-bordered md:w-1/2", data: { action: 'input->search#search'} %>
          </div>
          <%= render 'shared/simple_dialog_modal', modal_id: "categories" do %>
            <div class="grid gap-4 my-2" >
              <%= f.label :category_id, "Categoria" %>
              <%= f.collection_select :category_id_eq, Category.user_global(current_user).incomes, :id, :name, { prompt: "Selecione a categoria" }, class: "select select-sm select-bordered w-full max-w-xs", include_blank: true, onchange: 'categories.close()', data: { action: 'change->search#search'} %>
            </div>
          <% end %>
          <%= render 'shared/simple_dialog_modal', modal_id: "data" do %>
            <h3 class="font-semibold mb-4 text-lg">Selecione o Periodo:</h3>
            <div class="grid gap-1 md:gap-4 my-2">
              <%= f.label :date, "De" %>
              <%= f.date_field :date_gteq, class: "input input-sm input-bordered w-full max-w-xs" %>
              <%= f.label :date_at, "Até" %>
              <%= f.date_field :date_lteq, class: "input input-sm input-bordered w-full max-w-xs" %>
            </div>
            <%= button_tag "Pesquisar", type: "button", class: "btn btn-secondary btn-sm w-full mt-4 mr-4", data: { action: 'click->search#search'}, onclick: "data.close()" %>
          <% end %>
        </div>
        <div class="items-center justify-center md:justify-start hidden" data-search-target="clearButton">
          <%= link_to 'Limpar', incomes_path, class: "btn btn-secondary btn-sm md:w-1/3 w-full mt-2" %>
        </div>
      <% end %>
    </div>
    <%= turbo_frame_tag :results, data: { turbo_action: :advance } do %>
      <div id="incomes" class="overflow-x-auto">
        <%= render 'shared/desktop_table', values: @incomes %>
        <%= render 'shared/mobile_table', values: @incomes %>
      </div>
    <% end %>
    <div >
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>

app/views/incomes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova Receita</h1>
  <%= render "form", income: @income %>
</div>

app/views/incomes/show.html.erb
<div class="card bg-base-100 md:w-1/2 p-6 shadow-lg mx-auto relative">
  <div class="flex w-full justify-between absolute left-0 -right-3 top-0 p-3">
    <%= link_to incomes_path, class: "btn btn-sm btn-info flex h-8 w-8" do %>
      <i class="fa fa-list text-white" aria-hidden="true"></i>
    <% end %>
    <%= button_to @income, method: :delete, class: "btn btn-sm btn-error h-8 w-8", data: { turbo_confirm: 'Tem certeza?' } do %>
      <i class="fas fa-trash-alt text-gray-100"></i>
    <% end %>
  </div>
  <div class="card-body md:items-center md:text-center">
    <h2 class="card-title">Detalhes da receita:</h2>
    <%= render @income %>
  </div>
  <div class="card-actions items-center justify-between">
    <%= link_to incomes_path, class: "btn btn-secondary" do %>
      <i class="fa fa-arrow-left"></i>
      <span>Voltar</span>
    <% end %>
    <%= link_to edit_income_path(@income), class: "btn btn-primary" do %>
      <i class="fa fa-pencil"></i>
      <span>Editar</span>
    <% end %>
  </div>
</div>